spring:
  mvc:
    favicon:
      enabled: false

    view:

      prefix: /WEB-INF/view/
      suffix: .jsp

  messages:
    basename: text/welcome

  h2:
    console:
      enabled: true

server:
  port: 9090

property:
  test:
    name: property depth test

propertyTest: test
propertyTestList: a,b,c
